SERVER:
  HOST: "localhost"
  PORT: "5040"

METRICS:
  HOST: "localhost"
  PORT: "9090"

PERSISTENCE:
  JOURNAL:
    PATH1: "./data/journal_0.aof"
    PATH2: "./data/journal_1.aof"
    POLICY: "everysec"
  SNAPSHOT:
    PATH: "./data/dump.gob"
    INTERVAL: 60s

MEMORY:
  MAX_SIZE: 0 # bytes, 0 = unlimited

DEBUG:
  PPROF:
    ENABLE: True
    HOST: "localhost"
    PORT: "6060"
